INCDIR = -I../include/linux
LDDIR = -L../ -L../external/linux 
LDMOULE = -lsdfs -lgtest -lpthread

OBJS = testrtable.o testdest.o testrentity.o testSerializer.o testprocesslist.o testSiBlock.o testBlocklist.o

all: $(OBJS)

$(OBJS): %.o: %.cpp
	g++ -g $< -o $@ $(INCDIR) $(LDDIR) $(LDMOULE) 
	./$@

clean : 
	rm -f *.o
