#include "rtable.h"


/*rtable::rtable(droute * router){
	m_router = router;
}
*/
rtable::rtable(){
	//m_router = router;
}

rtable::~rtable(){
	
}
int rtable::findpath(string path)
{
	char hash[rentry::hash_size]; 
	rentry::hash(path, hash);
	int i;
	int size = m_routeitems.size();
	for(i = 0; i< size;i++)
		if(m_routeitems[i]->match(hash))
			break;
	
	if(i>=size)
		i=-1;

    return i;
}

vector <dest *> * rtable::getItemDests(int i){
	return m_routeitems[i]->getDests();
}

bool rtable::addpath(string path, string destinations)
{
	if(findpath(path)!=-1)
		return false;
	rentry *newitem = new rentry(path);
	newitem->refreshdests(destinations);
	
	m_routeitems.push_back(newitem);
    return true;
}

bool rtable::deletepath(string path)
{
	int i = findpath(path);
	if(i==-1)
		return false;
		
	delete m_routeitems[i];
	m_routeitems.erase(m_routeitems.begin()+i);
	return true;	    
}
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B39 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int rtable::updatepathdestination(string path, string destination)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B47 begin
{
    return 0;
}
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int rtable::removepathdestination(string path, string destination)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B68 begin
{
    return 0;
}
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B68 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
