#include "rtable.h"




char rtable::findpath(char path)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--108--38-71--66a2fe6b:14e66efdbed:-8000:0000000000000A57 begin
{
    return 'x';
}
// section 10--108--38-71--66a2fe6b:14e66efdbed:-8000:0000000000000A57 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int rtable::addpath(char path, char destination)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B35 begin
{
    return 0;
}
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B35 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int rtable::deletepath(char path)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B39 begin
{
    return 0;
}
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B39 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int rtable::updatepathdestination(char path, int destination)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B47 begin
{
    return 0;
}
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int rtable::removepathdestination(char path, char destination)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B68 begin
{
    return 0;
}
// section 10--108--40-15--332735f8:14e674c63c5:-8000:0000000000000B68 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
